### ISSUE TITLE
Error in call to target 'sam2.sam2_video_predictor.SAM2VideoPredictor'

### ISSUE THREAD

**Issue by rdemets** [Krishvraman/napari-SAMV2#1]
Hi, 

I followed the instructions to install the plugin, then I got several errors. 
The first one was when I tried to open the plugin in Napari. 

I got : `OMP: Error #15: Initializing libomp140.x86_64.dll, but found libiomp5md.dll already initialized`, but I managed to fix it following [this link ](https://stackoverflow.com/questions/20554074/sklearn-omp-error-15-initializing-libiomp5md-dll-but-found-mk2iomp5md-dll-a) and by adding 
``import os
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"`` in the __main__.py of napari. 

Then I tried to open the Brain3D image from the sample images in napari, but I got the following error when I try to Initialize. 

`InstantiationException: Error in call to target 'sam2.sam2_video_predictor.SAM2VideoPredictor':
TypeError("SAM2Base.__init__() missing 3 required positional arguments: 'image_encoder', 'memory_attention', and 'memory_encoder'")
full_key: model`

I dont really know how to fix this. Thank you very much !

**Comment by Krishvraman** [comment]
Hi @rdemets ,

Were you able to install sam 2 without any issue from here ?  (https://github.com/facebookresearch/segment-anything-2.git)

Also, 
What is your python, GPU,  pytorch  and cuda versions ? 
From their website, the model needs minimum python>=3.10,  torch>=2.3.1 and torchvision>=0.18.1.

Currently, the encoding only supports 8 bit images. So napari Brain 3d might not be the best. Try converting it into 8 bit and then use for segmentation. I am planning to have this conversion take place inside the plugin for the next version release. 

Thanks !

**Comment by Krishvraman** [comment]
Hi @rdemets,

Thanks for raising the issue ! 

Looks like facebookresearch/sam2 have a new release in their repo. They now have sam 2.1 models and code.

I am able to reproduce your issue with the new sam2 code. 
I think the new code is not working with the old models. 

The current napari plugin only supports the previous version of this repo.  I will update the plugin soon. 

As a workaround, please install sam 2 code from a previous date like below,
-------------------------------------------------------------------------------
git clone https://github.com/facebookresearch/segment-anything-2.git
cd segment-anything-2

git rev-list -n 1 --before="30 days ago" HEAD                            (---- use any commits before the sam 2.1 commit in their repo)

git checkout <commit_hash>

pip install -e .

----------------------------------------------------------

The model currently supports only 8 bit embeddings. So napari brain 3d might not be the best. Try converting it into 8 bit stack and then test the plugin. I will update the plugin soon with sam 2.1 and 16 ,32 bit supports. 

Thanks !
